import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/Navbar";
import { NextUIProvider } from "@nextui-org/react";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="bg-backgroung h-max w-screen">
				<body className={`${inter.className} dark bg-background text-text flex h-screen`}>
			<NextUIProvider>
					<NavBar />
					<div className="mt-16 h-full w-screen bg-background">{children}</div>
					<Footer/>
			</NextUIProvider>
				</body>
		</html>
	);
}

